### ISSUE TITLE
Не открывает ссылку для аутентификации 

### ISSUE THREAD

**Issue by Just3F** [continuation-team/unity-ton-connect#1]
Если запускать игру из вьюшки телеги то при нажатии open wallet ничего не происходит. Если из бразуера обычного то все работает хорошо. Не уверен решается ли эта проблема на уровне кода, но тем не менее, без этого тон коннект не подключить никак.

**Comment by purpleguy99** [comment]
Я думаю чтo вам лучше использовать в вебиграх инструменты Tonconnect UI без SDK.

**Comment by Fisber** [comment]
такая же проблема и у меня, Можно как-то поподробнее разъяснить если не трудно?
