### ISSUE TITLE
unity tonkeeper login error

### ISSUE THREAD

**Issue by zhaokang56** [continuation-team/unity-ton-connect#2]
tonkeeper Wallet login returned an error message, id could not be resolved

![2024-04-08 2 31 38 PM](https://github.com/continuation-team/unity-ton-connect/assets/46038933/a0a62da3-a392-4c1c-939f-19e1d9d2c1f3)
![2024-04-08 2 31 22 PM](https://github.com/continuation-team/unity-ton-connect/assets/46038933/1293217c-947d-48af-adfc-1fd3a2948e48)

**Comment by purpleguy99** [comment]
fixed in 0.2.1
