### ISSUE TITLE
Issue when using WebGL

### ISSUE THREAD

**Issue by anhnq82** [continuation-team/unity-ton-connect#3]
I have integrated TON Connect and connected successfully on my unity project, but when building to Webgl, I can't connect to my wallet anymore. Do you know if I need a specific config?

**Comment by purpleguy99** [comment]
I updated the package, try again.

**Comment by purpleguy99** [comment]
https://github.com/continuation-team/unity-ton-connect/releases/tag/v0.2.3-alpha

**Comment by purpleguy99** [comment]
Also please in build settings, select the TC_minimal template

**Comment by anhnq82** [comment]
> Also please in build settings, select the TC_minimal template

It works. Thank you for being so supportive!
