### ISSUE TITLE
SendTransaction causes error DllNotFoundException: JustCRC32C_Native_x64.dll when confirm transaction

### ISSUE THREAD

**Issue by tiennvsolar** [continuation-team/unity-ton-connect#5]
![image](https://github.com/continuation-team/unity-ton-connect/assets/74697768/2d8217e4-3f80-4ade-a40c-02d63261f946)

**Comment by purpleguy99** [comment]
Update Asset from releases topic

**Comment by purpleguy99** [comment]
https://github.com/continuation-team/unity-ton-connect/releases/tag/v0.2.4-alpha
